# Generated by Django 5.2.4 on 2025-07-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptype',
            name='moisture_threshold',
            field=models.FloatField(blank=True, help_text='Minimum soil moisture % before irrigation is recommended', null=True),
        ),
        migrations.AddField(
            model_name='croptype',
            name='water_requirement',
            field=models.FloatField(blank=True, help_text='Crop water requirement in mm/day or other unit', null=True),
        ),
    ]
