# Generated by Django 5.2.4 on 2025-07-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0002_croptype_moisture_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilmoisturerecord',
            name='sensor_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the sensor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soilmoisturerecord',
            name='sensor_type',
            field=models.CharField(blank=True, help_text="Type of sensor (e.g., 'soil_moisture', 'temperature', 'humidity')", max_length=50, null=True),
        ),
    ]
